"""
Django settings for webapp project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import platform

BROKER_URL = 'django://'  



DEBUG = True

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*)p==1ch!qr=vyt2&r1d^67wi1oe%+@@0+m04ox*47r)nwce_y'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'gunicorn',
    'webapp.api',
    'webapp.appapi',
    'pagination',
    'webapp.account',
    'webapp.headquar',
    'webapp.agent',
    'webapp.scenic',
	'djcelery',
	'kombu.transport.django',
	'ckeditor',
	'ckeditor_uploader',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'pagination.middleware.PaginationMiddleware',
)

ROOT_URLCONF = 'webapp.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webapp.wsgi.application'



CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://localhost:6379",
        "OPTIONS": {
            "DB":4,
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'OPTIONS': {
            'timeout': 20,
        },
    }
}
#'''
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': 'csvt',
#        'USER':'root',
#        'PASSWORD':'doublecom2017',
#        'HOST':'',
#        'PORT':'',
#    }
#}   
#'''
CONFIG = os.path.join(BASE_DIR, 'manuf')
CONFIG2 = os.path.join(BASE_DIR, 'config.ini')
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

SMS_REALSEND = True

UCPAAS_SID = 'e46a4cef97433eb84f668330ee56121b'

UCPAAS_APPID = '02b697a25ac84fd5a5213d133c975447'

UCPAAS_TOKEN = '47d10633c566ae34e2ee9ba88c5af55a'


COMPONENT_APPID = 'wxd9103590a61f46e0'
COMPONENT_APPSECRET = '88f159fdeff76f0f04b05da6e98fd40c'

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(os.path.dirname(__file__), '..', 'static/ckeditor').replace('\\','/') 
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
  )

MEDIA_URL = '/uploads/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

AUTH_USER_MODEL = 'account.User' 

LOGIN_REDIRECT_URL = '/main/'

LOGOUT_URL = '/logout/'

LOGIN_URL = '/login/'

DATETIME_FORMAT = 'Y-m-d H:i'

CKEDITOR_CONFIGS = {
    'awesome_ckeditor': {
        'toolbar': 'full',
    },
}

CKEDITOR_UPLOAD_PATH = "/static/uploads/ckeditorimg/"
CKEDITOR_JQUERY_URL = '//cdn.bootcss.com/jquery/1.11.3/jquery.min.js'
